// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = {
	'start': {	
		/**
		 * Join tribes of likelly-minded people nearby!
		 */
		'text': string
		'buttons': {	
			/**
			 * Game rules
			 */
			'rules': string
			/**
			 * List tribes
			 */
			'list': string
		}
	}
	'rules': {	
		'apply': {	
			/**
			 * To join a tribe you like you must send application. 
					Tribe's chief and shaman will consider it and invite you to have a conversation with them. 
					If they decide that you allign with the tribe spirit well, they will let you join
			 */
			'text': string
			'buttons': {	
				/**
				 * Who is shaman?
				 */
				'onShaman': string
				/**
				 * Who is chief?
				 */
				'onChief': string
				/**
				 * What's next?
				 */
				'next': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
		'onChief': {	
			/**
			 * Chief is the most charismatic person in the tribe. Their duties is to maintain tribe's integrity.
			 */
			'text': string
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
		'onShaman': {	
			/**
			 * Shaman is the most wise person in the tribe. Thier duities is to assist tribe's chief.
			 */
			'text': string
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
		'inTribe': {	
			/**
			 * Now, when you're in tribe you can participate in brainstorm and tribe's quests
			 */
			'text': string
			'buttons': {	
				/**
				 * What is brainstorm?
				 */
				'onBrainsotrm': string
				/**
				 * Who are quests?
				 */
				'onQuests': string
				/**
				 * ← Back
				 */
				'back': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
		'onBrainsotrm': {	
			/**
			 * In a brainstorm you will suggest activities for the tribe and vote for activities you like
					You will be notified when next brainstorm is on the horizon!
			 */
			'text': string
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
		'onQuests': {	
			/**
			 * Quests are tribe's activities. Those could be practical tasks, or just gatherings to hang out with your fellows
			 */
			'text': string
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': string
				/**
				 * Let's start!
				 */
				'start': string
			}
		}
	}
	'tribesList': {	
		/**
		 * To find tribes nearby we need acces to your location
		 */
		'requestLocationText': string
		/**
		 * Share my location
		 */
		'requestLocation': string
		/**
		 * Send application
		 */
		'apply': string
	}
}

export type TranslationFunctions = {
	'start': {	
		/**
		 * Join tribes of likelly-minded people nearby!
		 */
		'text': () => LocalizedString
		'buttons': {	
			/**
			 * Game rules
			 */
			'rules': () => LocalizedString
			/**
			 * List tribes
			 */
			'list': () => LocalizedString
		}
	}
	'rules': {	
		'apply': {	
			/**
			 * To join a tribe you like you must send application. 
					Tribe's chief and shaman will consider it and invite you to have a conversation with them. 
					If they decide that you allign with the tribe spirit well, they will let you join
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * Who is shaman?
				 */
				'onShaman': () => LocalizedString
				/**
				 * Who is chief?
				 */
				'onChief': () => LocalizedString
				/**
				 * What's next?
				 */
				'next': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
		'onChief': {	
			/**
			 * Chief is the most charismatic person in the tribe. Their duties is to maintain tribe's integrity.
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
		'onShaman': {	
			/**
			 * Shaman is the most wise person in the tribe. Thier duities is to assist tribe's chief.
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
		'inTribe': {	
			/**
			 * Now, when you're in tribe you can participate in brainstorm and tribe's quests
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * What is brainstorm?
				 */
				'onBrainsotrm': () => LocalizedString
				/**
				 * Who are quests?
				 */
				'onQuests': () => LocalizedString
				/**
				 * ← Back
				 */
				'back': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
		'onBrainsotrm': {	
			/**
			 * In a brainstorm you will suggest activities for the tribe and vote for activities you like
					You will be notified when next brainstorm is on the horizon!
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
		'onQuests': {	
			/**
			 * Quests are tribe's activities. Those could be practical tasks, or just gatherings to hang out with your fellows
			 */
			'text': () => LocalizedString
			'buttons': {	
				/**
				 * ← Back
				 */
				'back': () => LocalizedString
				/**
				 * Let's start!
				 */
				'start': () => LocalizedString
			}
		}
	}
	'tribesList': {	
		/**
		 * To find tribes nearby we need acces to your location
		 */
		'requestLocationText': () => LocalizedString
		/**
		 * Share my location
		 */
		'requestLocation': () => LocalizedString
		/**
		 * Send application
		 */
		'apply': () => LocalizedString
	}
}

export type Formatters = {}
