version: '3.9'
services:
  mongodb:
    image: mongo:5.0.4-focal
    # ports:
    #   - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - mongo-data:/data/db
    networks:
      - tribalizm
networks:
  tribalizm:
    name: tribalizm
volumes:
  mongo-data:
    driver: local
      
