FROM node:14.18.2-alpine3.14
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "yarn.lock", "/usr/src/app/"]
RUN yarn install --production --silent
COPY . .
# RUN chown -R node /usr/src/app
USER node
CMD yarn start:admin
