---
- hosts: bot
  vars:
    version: '{{ lookup("env", "npm_package_version") }}'
    registry: '{{ lookup("env", "REGISTRY") }}'
    db_user: '{{ lookup("env", "DB_USER") }}'
    db_pass: '{{ lookup("env", "DB_PASS") }}'
    db_host: '{{ lookup("env", "DB_HOST") }}'
    db: '{{ lookup("env", "DB") }}'
    bot_token: '{{ lookup("env", "BOT_TOKEN") }}'
    domain: '{{ lookup("env", "DOMAIN") }}'
    app_port: '{{ lookup("env", "PORT") }}'
    network: '{{ lookup("env", "NETWORK") }}'
    log_level: trace

  tasks:
    - name: '--- Debug ---'
      tags: [debug]
      debug:
        msg:
          'Vars: registry: {{ registry }}; version: {{ version }}; port: {{ app_port }};
          db_user: {{ db_user }}; db_pass: {{ db_pass }}; db_host: {{ db_host }}; db: {{ db }};
          bot_token: {{ bot_token }}; domain: {{ domain }};  network: {{ network }}; '

    - name: Deploy MongoDB
      tags: [mongo]
      docker_container:
        name: mongodb
        image: mongo:5.0.4-focal
        volumes:
          - mongo-data:/data/db
        networks:
          - name: '{{ network }}'
        restart_policy: always
        ports:
          - '2323:27017'
        env:
          MONGO_INITDB_ROOT_USERNAME: '{{ db_user | string}}'
          MONGO_INITDB_ROOT_PASSWORD: '{{ db_pass | string}}'
        log_driver: loki
        log_options:
          loki-url: 'http://localhost:3100/loki/api/v1/push'
          loki-retries: '5'
          loki-batch-size: '400'
        # to get rid of warnings:
        container_default_behavior: no_defaults
        network_mode: '{{ network }}'

    - name: install AWS ECR credentials helper
      become: yes
      apt:
        name:
          - amazon-ecr-credential-helper
          - awscli
        update_cache: yes

    - name: Log in to AWS ECR
      shell: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin '{{ registry | string }}'

    - name: Deploy Tribalizm bot
      docker_container:
        name: tribalizm-bot
        image: '{{ registry | string }}/tribalizm-bot:{{ version | string }}'
        networks:
          - name: '{{ network }}'
        ports:
          - '{{ app_port | string }}:3000'
        restart_policy: always
        env:
          DB_USER: '{{ db_user | string}}'
          DB_PASS: '{{ db_pass | string}}'
          DB_HOST: '{{ db_host | string}}'
          DB: '{{ db | string}}'
          DOMAIN: '{{ domain | string}}'
          BOT_TOKEN: '{{ bot_token | string}}'
          LOG_LEVEL: '{{ log_level | string}}'
        log_driver: loki
        log_options:
          loki-url: 'http://localhost:3100/loki/api/v1/push'
          loki-retries: '5'
          loki-batch-size: '400'
        # to get rid of warnings:
        container_default_behavior: no_defaults
        network_mode: '{{ network }}'

    - name: Set Cron job to check tasks queue
      cron:
        name: check tasks queue
        job: 'curl localhost:{{ app_port | string }}/check-queue > /dev/null'

    - name: Pull Tribalizm Admin image
      tags: ['pull']
      docker_image:
        name: '{{ registry | string }}/tribalizm-admin:{{ version | string }}'
        source: pull
