---
- hosts: all  
  tasks:

  - name: install docker 
    become: yes
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add user permissions
    become: yes
    shell: "usermod -aG docker {{ ansible_ssh_user }}"

  # Installs Docker SDK
  - name: install python package manager
    become: yes
    apt:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{ ansible_ssh_user }}"
    pip:
      name:
        - docker
        - docker-compose